<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Streamer Pro</AssemblyName>
    <Product>Streamer Pro</Product>
    <Version>1.5</Version>
    <AssemblyVersion>1.5.0.0</AssemblyVersion>
    <FileVersion>1.5.0.0</FileVersion>
    <ApplicationIcon>streamer.ico</ApplicationIcon>
    <PackageIcon></PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ffmpeg.exe" />
    <None Remove="ffprobe.exe" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="streamer.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="streamer.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
