<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Streamer Pro</AssemblyName>
    <Product>Streamer Pro</Product>
    <Version>2.0.2</Version>
    <AssemblyVersion>2.0.2.0</AssemblyVersion>
    <FileVersion>2.0.2.0</FileVersion>
    <ApplicationIcon>streamer.ico</ApplicationIcon>
    <PackageIcon></PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ffmpeg.exe" />
    <None Remove="ffprobe.exe" />
    <None Remove="streamerpro.png" />
    <None Remove="streamerpro.svg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ffprobe.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="streamer.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="streamerpro.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="streamerpro.png" />
    <Content Include="streamerpro.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="streamer.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
